	<?php include('mods/banner.php') ?>
	<?php include('mods/about.php') ?>
	<?php include('mods/services.php') ?>
	<?php include('mods/team.php') ?>
	<?php include('mods/callout.php') ?>
	<?php include('mods/testimonial.php') ?>
	<?php include('mods/contact.php') ?>
	<?php include('mods/map.php') ?>
	<?php include('mods/logos.php') ?>